# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  db:
    image: postgres:alpine
    environment: 
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
  apiguilherme:
    image: apiguilherme
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment: 
      DBServe: db